theme: jekyll-theme-primer
title: Ugur Bocegi
description: Personal website and portfolio
url: "https://uguebocegi.github.io"
baseurl: "/ugurbocegi"

# Jekyll settings
markdown: kramdown
highlighter: rouge
